require "core.plugins"
require "config.options"
require "config.keymaps"
require "core.cmp"
require "core.lsp"
require "core.telescope"
require "core.gitsigns"
require "core.treesitter"
require "core.autopairs"
require "core.comment"
-- require "core.nvimtree"
-- require "core.bufferline"
require "core.cokeline"
require "config.colors"
require "core.lualine"
require "core.toggleterm"
require "core.project"
require "core.indentline"
require "core.alpha"
require "core.whichkey"
require "config.autocommands"
require "core.illuminate"
require "core.jaq"
require "core.tmux-navigation"
require "core.colorizer"
require "core.neoscroll"
require "core.bqf"
require "core.signature"
require "core.numb"
require "core.matchup"
require "core.neogen"
require "core.docs-view"
require "core.transparent"

vim.cmd('source ~/.config/nvim/lua/config/functions.vim')
