local status_ok, transparent = pcall(require, "transparent")
if not status_ok then
	return
end

transparent.setup({
  groups = { -- table: default groups
    'Normal', 'NormalNC', 'Comment', 'Constant', 'Special', 'Identifier',
    'Statement', 'PreProc', 'Type', 'Underlined', 'Todo', 'String', 'Function',
    'Conditional', 'Repeat', 'Operator', 'Structure', 'LineNr', 'NonText',
    'SignColumn', 'CursorLineNr', 'EndOfBuffer',
  },
  extra_groups = { -- table/string: additional groups that should be cleared
    -- In particular, when you set it to 'all', that means all available groups

    -- example of akinsho/nvim-bufferline.lua
    "NormalFloat",
    "NvimTreeNormal",
    "BufferlineBufferSelected",
    "BufferLineFill",
    "BufferLineBackground",
    "BufferLineSeparator",
    "BufferLineIndicatorSelected",
    "CursorLineSign",
    "CursorLineFold",
    "NeoTreeWinSeparator",
    "NeoTreeVertSplit",
    "Folded",
    "FoldColumn",
    "VertSplit",
    "NvimTreeVertSplit",
    "NvimTreeWinSeparator",
    "NvimTreeEndOfBuffer",
    "StatusLine",
    "StatusLineNC",
    "GitSignsAdd",
    "GitSignsDelete",
    "GitSignsChange",
    "GitSignsCurrentLineBlame",
    "MsgSeparator",
    "MsgArea",
    "FloatBorder",
    "FloatShadow",
    "FloatShadowThrough",
    "ModeMsg",
    "WarningMsg",
    "Pmenu",
    "PmenuSel",
    "PmenuKind",
    "PmenuKindSel",
    "PmenuExtra",
    "PmenuExtraSel",
    "PmenuSbar",
    "PmenuThumb",
    "TabLine",
    "TabLineSel",
    "TabLineFill",
    "TelescopeNormal",
    "VisualNOS",
    "BufferInactiveTarget",
    "BufferInactiveSign",
    "BufferInactiveMod",
    "BufferInactiveIndex",
    "BufferInactive",
    "BufferVisibleTarget",
    "BufferVisibleSign",
    "BufferVisibleMod",
    "BufferVisibleIndex",
    "BufferCurrentTarget",
    "BufferCurrentSign",
    "BufferCurrentMod",
    "BufferCurrentIndex",
    "BufferCurrent",
    "WhichKeyFloat",
    "DiagnosticSignError",
    "DiagnosticSignWarn",
    "DiagnosticSignInfo",
    "DiagnosticSignHint",
    "NormalFloat",
    "DiagnosticSignError",
    "DiagnosticSignWarn",
    "DiagnosticSignHint",
    "DiagnosticSignInfo",
    "LspDiagnosticsUnderlineError",
    "LspDiagnosticsUnderlineWarning",
    "LspDiagnosticsUnderlineInformation",
    "LspDiagnosticsUnderlineHint",
    "LspReferenceText",
    "LspReferenceRead",
    "LspReferenceWrite",
    "MatchBackground",
  },
  exclude_groups = {}, -- table: groups you don't want to clear
})
